version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD : root
      POSTGRES_USER : postgres
      POSTGRES_DB : nest-pos-be
  app:
    image: nestjs-app
    ports:
      - 3500:3100